# Import modules
import sys, os, arcpy

# Set workspace 
arcpy.env.workspace = "V:/env859_ps4/Data"

# Enable overwrite 
arcpy.env.overwriteOutput = True 

# Setting local variables
in_features = "streams.shp"

# Making output file generated by the code and buffer distance
buffer_distance = arcpy.GetParameterAsText(0) + " meters"

# Getting just the distance so that it can be appended to the file name
# I wasn't sure if adding another parameter function overwrites the previous one, but it 
# was the only way I could find to remove the word "meters" from the file name
buff_dist = arcpy.GetParameterAsText(0)
out_feature_class = "V:/env859_ps4/Scratch/buff_{}m.shp".format(buff_dist)

# Run Buffer tool and print messages
arcpy.Buffer_analysis(in_features, out_feature_class, buffer_distance,"", "", "ALL", "", "PLANAR")
print(arcpy.GetMessages())


